# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - production

env:
  ITCH_USER: kaosumaru
  ITCH_GAME: umbra-et-lux
  ITCH_CHANNEL: html5

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PRODUCTION }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
        env:
          NODE_ENV: production
          VITE_SERVER_URL: https://umbra-et-lux.fly.dev/

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

      - name: Upload to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ env.ITCH_CHANNEL }}
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: test/
          VERSION: 1.0.0
